language: python
cache: pip
dist: xenial

matrix:
  include:
   - env: TOXENV=py36-dj22-sqlite-elasticsearch2 INSTALL_ELASTICSEARCH2=yes
     python: 3.6
  allow_failures:
    # Ignore failures on Elasticsearch tests because ES on Travis is intermittently flaky
    - env: TOXENV=py36-dj22-sqlite-elasticsearch2 INSTALL_ELASTICSEARCH2=yes

# Package installation
install:
  - pip install tox codecov
  - 'if [[ -n "$INSTALL_ELASTICSEARCH2" ]]; then ./scripts/travis/install_elasticsearch2.sh; fi'

# Run the tests
script:
  tox

after_success:
  - codecov -F backend

# Who to notify about build results
notifications:
  slack:
    secure: Y/UERaVnR+RL2dOqLR0Nc60JdGkejQ1Ae5zvPRYdDiMIGSv/1KC3T5Dp8NxamqIlozbQNmRaZD+i4AdX60g1M3xlB9DMINzY584YK0X2T2S28+xIgE0MQJijbpfbk2veV8PMeA6EHNpG4zoT+4sbcSyljt9TPcYTTTiTB8rAtc0=

# bump Travis: 1
